const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST'
const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS'
const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE'

const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'

const LOGOUT = 'USERS_LOGOUT'


export default {
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,

  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,

  LOGOUT,
};
